# Generated by Django 6.0 on 2026-01-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artiste',
            name='nom',
            field=models.CharField(default='Nom inconnu', max_length=150),
        ),
    ]
