# Generated by Django 6.0 on 2026-01-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0002_artiste_date_naissance_artiste_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='nom',
            field=models.CharField(max_length=150),
        ),
    ]
