# Generated by Django 6.0 on 2026-01-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0003_alter_artiste_nom'),
    ]

    operations = [
    ]
