# Generated by Django 6.0.1 on 2026-01-17 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0004_fix_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panier',
            options={'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterModelOptions(
            name='panieritem',
            options={'verbose_name': 'Article panier', 'verbose_name_plural': 'Articles panier'},
        ),
        migrations.AlterUniqueTogether(
            name='panieritem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commande',
            name='geree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_gerees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expositions', to='galerie.lieu'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='oeuvre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commande', to='galerie.oeuvre'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oeuvres', to='galerie.categorie'),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panieritem',
            name='oeuvre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_panier', to='galerie.oeuvre'),
        ),
        migrations.AddConstraint(
            model_name='lignecommande',
            constraint=models.UniqueConstraint(fields=('commande', 'oeuvre'), name='unique_commande_oeuvre'),
        ),
        migrations.AddConstraint(
            model_name='panieritem',
            constraint=models.UniqueConstraint(fields=('panier', 'oeuvre'), name='unique_panier_oeuvre'),
        ),
        migrations.AlterModelTable(
            name='panier',
            table='panier',
        ),
        migrations.AlterModelTable(
            name='panieritem',
            table='panier_item',
        ),
    ]
