# Generated by Django 6.0.1 on 2026-01-26 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0005_alter_panier_options_alter_panieritem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notif', models.CharField(choices=[('exposition', 'Invitation à exposition'), ('mise_a_jour', 'Mise à jour'), ('information', 'Information'), ('alerte', 'Alerte')], default='information', max_length=20)),
                ('statut', models.CharField(choices=[('non_lue', 'Non lue'), ('lue', 'Lue')], default='non_lue', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('exposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='galerie.exposition')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
