# Generated by Django 6.0.1 on 2026-01-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='reference_transaction',
        ),
        migrations.AddField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('carte_bancaire', 'Carte bancaire'), ('virement', 'Virement'), ('especes', 'Espèces'), ('paypal', 'PayPal')], default='carte_bancaire', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('succes', 'Succès'), ('echec', 'Échec'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
