# Generated by Django 6.0.1 on 2026-01-27 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0007_remove_paiement_mode_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('gratuit', 'Gratuit'), ('standard', 'Standard (15€)'), ('premium', 'Premium (25€)')], default='gratuit', max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=100)),
                ('stock_restant', models.IntegerField(default=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='galerie.exposition')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='AchatTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('date_visite_prevu', models.DateField(blank=True, null=True)),
                ('numero_confirmation', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acheteurs_tickets', to='galerie.exposition')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='galerie.ticket')),
            ],
            options={
                'verbose_name': 'Achat Ticket',
                'verbose_name_plural': 'Achats Tickets',
                'db_table': 'achat_ticket',
                'ordering': ['-date_achat'],
            },
        ),
    ]
