# Generated by Django 6.0.1 on 2026-01-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0008_ticket_achatticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
